SET IDENTITY_INSERT [dbo].[Products] ON
INSERT INTO [dbo].[Products] ([UPC], [Name], [Price], [Description], [Department]) VALUES (1, N'Milk', CAST(3.46 AS Decimal(18, 2)), N'Whole Milk Gallon', N'Grocery')
INSERT INTO [dbo].[Products] ([UPC], [Name], [Price], [Description], [Department]) VALUES (2, N'Bacon', CAST(4.48 AS Decimal(18, 2)), N'Thick Slide Bacon Smoked 16oz package', N'Grocery')
INSERT INTO [dbo].[Products] ([UPC], [Name], [Price], [Description], [Department]) VALUES (3, N'White Rice', CAST(1.54 AS Decimal(18, 2)), N'Long Grain Rice, 32oz bag', N'Grocery')
INSERT INTO [dbo].[Products] ([UPC], [Name], [Price], [Description], [Department]) VALUES (4, N'Cereal', CAST(4.78 AS Decimal(18, 2)), N'Ca''pn Crunch''s 20oz', N'Grocery')
INSERT INTO [dbo].[Products] ([UPC], [Name], [Price], [Description], [Department]) VALUES (5, N'Muffins', CAST(4.98 AS Decimal(18, 2)), N'Lemon Muffins, 14oz, 4 count', N'Grocery')
INSERT INTO [dbo].[Products] ([UPC], [Name], [Price], [Description], [Department]) VALUES (6, N'Roku', CAST(29.00 AS Decimal(18, 2)), N'Streaming Media Player', N'Electronics')
INSERT INTO [dbo].[Products] ([UPC], [Name], [Price], [Description], [Department]) VALUES (7, N'Xbox Controller', CAST(49.49 AS Decimal(18, 2)), N'Microsoft Xbox Wireless Controler - Blue', N'Electronics')
INSERT INTO [dbo].[Products] ([UPC], [Name], [Price], [Description], [Department]) VALUES (8, N'Gaming Headset', CAST(38.80 AS Decimal(18, 2)), N'ASTRO Gaming Headset  - Green / Black', N'Electronics')
INSERT INTO [dbo].[Products] ([UPC], [Name], [Price], [Description], [Department]) VALUES (9, N'Nintendo Switch', CAST(339.97 AS Decimal(18, 2)), N'Nintendo Switch Console', N'Electronics')
INSERT INTO [dbo].[Products] ([UPC], [Name], [Price], [Description], [Department]) VALUES (10, N'TV', CAST(797.99 AS Decimal(18, 2)), N'Samsung 55" QLED 4K smart TV', N'Electronics')
INSERT INTO [dbo].[Products] ([UPC], [Name], [Price], [Description], [Department]) VALUES (11, N'Uno', CAST(5.99 AS Decimal(18, 2)), N'Color and number matching card game', N'Toys')
INSERT INTO [dbo].[Products] ([UPC], [Name], [Price], [Description], [Department]) VALUES (12, N'Bowling Set', CAST(23.88 AS Decimal(18, 2)), N'Plat Day Jumbo Bowling Set', N'Toys')
INSERT INTO [dbo].[Products] ([UPC], [Name], [Price], [Description], [Department]) VALUES (13, N'Dart Gun', CAST(39.82 AS Decimal(18, 2)), N'Dart Blaster - shoots over 125FT', N'Toys')
INSERT INTO [dbo].[Products] ([UPC], [Name], [Price], [Description], [Department]) VALUES (14, N'Jenga', CAST(10.27 AS Decimal(18, 2)), N'Hard Blocks, Stacking game', N'Toys')
INSERT INTO [dbo].[Products] ([UPC], [Name], [Price], [Description], [Department]) VALUES (15, N'Mystery Capsule', CAST(6.97 AS Decimal(18, 2)), N'5 Surprise mini brands Series 3', N'Toys')
INSERT INTO [dbo].[Products] ([UPC], [Name], [Price], [Description], [Department]) VALUES (16, N'Table lamp', CAST(29.88 AS Decimal(18, 2)), N'Ceramic Table Lamp - White', N'Home')
INSERT INTO [dbo].[Products] ([UPC], [Name], [Price], [Description], [Department]) VALUES (17, N'Book shelf', CAST(119.99 AS Decimal(18, 2)), N'Bookshelf with 3 drawers', N'Home')
INSERT INTO [dbo].[Products] ([UPC], [Name], [Price], [Description], [Department]) VALUES (18, N'Cube storage', CAST(44.97 AS Decimal(18, 2)), N'Cube storage organizer - balck ', N'Home')
INSERT INTO [dbo].[Products] ([UPC], [Name], [Price], [Description], [Department]) VALUES (19, N'Barstool set', CAST(69.99 AS Decimal(18, 2)), N'Metal frame couter stool - 2 units', N'Home')
INSERT INTO [dbo].[Products] ([UPC], [Name], [Price], [Description], [Department]) VALUES (20, N'Coffee table', CAST(85.11 AS Decimal(18, 2)), N'Crastsman mordern coffee table', N'Home')
INSERT INTO [dbo].[Products] ([UPC], [Name], [Price], [Description], [Department]) VALUES (21, N'Dog Treat', CAST(3.48 AS Decimal(18, 2)), N'Milk-Bone Dog Biscuits 8oz bag', N'Pets')
INSERT INTO [dbo].[Products] ([UPC], [Name], [Price], [Description], [Department]) VALUES (22, N'Cat Litter Box', CAST(10.58 AS Decimal(18, 2)), N'Vibrant Life High Sided Hideout Cat - Blue', N'Pets')
INSERT INTO [dbo].[Products] ([UPC], [Name], [Price], [Description], [Department]) VALUES (23, N'Scratching Post', CAST(17.98 AS Decimal(18, 2)), N'Vibrant Life Deluxe Jute Cat Scratching Post with Arch Rubber Massager', N'Pets')
INSERT INTO [dbo].[Products] ([UPC], [Name], [Price], [Description], [Department]) VALUES (24, N'Dog Kennel', CAST(30.62 AS Decimal(18, 2)), N'Petmate Plastic Dog Kennel, Tan & Green, 24"L', N'Pets')
INSERT INTO [dbo].[Products] ([UPC], [Name], [Price], [Description], [Department]) VALUES (25, N'Cat Food', CAST(15.88 AS Decimal(18, 2)), N'Purina Pro Plan Urinary Tract Cat Food, Chicken and Rice Formula, 3.5 lb. Bag', N'Pets')
INSERT INTO [dbo].[Products] ([UPC], [Name], [Price], [Description], [Department]) VALUES (26, N'Cold Medicine', CAST(7.73 AS Decimal(18, 2)), N'Equate Daytime And Nighttime Softgel 48c', N'Pharmacy')
INSERT INTO [dbo].[Products] ([UPC], [Name], [Price], [Description], [Department]) VALUES (27, N'Allergy Relief', CAST(6.00 AS Decimal(18, 2)), N'Allegra Adult 24HR Tablet, Allergy Relief, 5 Count, 180 mg', N'Pharmacy')
INSERT INTO [dbo].[Products] ([UPC], [Name], [Price], [Description], [Department]) VALUES (28, N'COVID-19 Test', CAST(19.88 AS Decimal(18, 2)), N'BinaxNOW COVID-19 Antigen Self Test by Abbott (2 Count)', N'Pharmacy')
INSERT INTO [dbo].[Products] ([UPC], [Name], [Price], [Description], [Department]) VALUES (29, N'Alcohol Liquid', CAST(6.22 AS Decimal(18, 2)), N'Equate 91% Isopropyl Alcohol Liquid Antiseptic, 32 fl oz, Twin Pack', N'Pharmacy')
INSERT INTO [dbo].[Products] ([UPC], [Name], [Price], [Description], [Department]) VALUES (30, N'First Aid Kit', CAST(11.88 AS Decimal(18, 2)), N'Equate 140pc All Purpose First Aid Kit', N'Pharmacy')
INSERT INTO [dbo].[Products] ([UPC], [Name], [Price], [Description], [Department]) VALUES (31, N'Floor Mats', CAST(18.88 AS Decimal(18, 2)), N'Genuine Dickies 80030DCWDI Automotive Floor Mats Trim to Fit All-Weather Rubber, Black, 4 Pieces', N'Auto')
INSERT INTO [dbo].[Products] ([UPC], [Name], [Price], [Description], [Department]) VALUES (32, N'Steering Wheel Cover', CAST(16.98 AS Decimal(18, 2)), N'Genuine Dickies Classics Steering Wheel Cover Universal, Pinstripe Black', N'Auto')
INSERT INTO [dbo].[Products] ([UPC], [Name], [Price], [Description], [Department]) VALUES (33, N'Booster Cables Set', CAST(20.00 AS Decimal(18, 2)), N'EverStart Travel Pro Safety Kit, Emergency, Roadside Assistance, Booster Cables', N'Auto')
INSERT INTO [dbo].[Products] ([UPC], [Name], [Price], [Description], [Department]) VALUES (34, N'Car Care Kit', CAST(13.38 AS Decimal(18, 2)), N'Armor All Complete Car Care Kit (4 Pieces), Car Cleaning', N'Auto')
INSERT INTO [dbo].[Products] ([UPC], [Name], [Price], [Description], [Department]) VALUES (35, N'Wiper Blades 22', CAST(24.53 AS Decimal(18, 2)), N'TRICO Gold 2 Pack All Weather Automotive Replacement Wiper Blades 22 and 22 Inch (18-2222)', N'Auto')
INSERT INTO [dbo].[Products] ([UPC], [Name], [Price], [Description], [Department]) VALUES (36, N'Johnie Walker', CAST(35.98 AS Decimal(18, 2)), N'Johnnie Walker Black Label Blended Scotch Whisky, 750 mL, 40% ABV', N'Alcohol')
INSERT INTO [dbo].[Products] ([UPC], [Name], [Price], [Description], [Department]) VALUES (37, N'Marlboro', CAST(26.00 AS Decimal(18, 2)), N'Marlboro 100s Box cigarettes, 1 carton', N'Tobacco')
SET IDENTITY_INSERT [dbo].[Products] OFF
